tripadvisor_dict = {"Decode Ann Arbor": "https://www.tripadvisor.com/Attraction_Review-g29556-d11657758-Reviews-Decode_Ann_Arbor-Ann_Arbor_Michigan.html",
"Decode Ypsilanti": "https://www.tripadvisor.com/Attraction_Review-g42837-d15607690-Reviews-Decode_Ypsilanti-Ypsilanti_Michigan.html",
"Ann Arbor Hands-On Museum": "https://www.tripadvisor.com/Attraction_Review-g29556-d268545-Reviews-Ann_Arbor_Hands_On_Museum-Ann_Arbor_Michigan.html",
"University of Michigan": "https://www.tripadvisor.com/Attraction_Review-g29556-d107760-Reviews-University_of_Michigan-Ann_Arbor_Michigan.html",
"Kerrytown Market & Shops": "https://www.tripadvisor.com/Attraction_Review-g29556-d8661397-Reviews-Kerrytown_Markets_and_Shops-Ann_Arbor_Michigan.html",
"Breakout Escape Rooms - Ann Arbor": "https://www.tripadvisor.com/Attraction_Review-g29556-d8651846-Reviews-Breakout_Escape_Rooms_Ann_Arbor-Ann_Arbor_Michigan.html",
"Matthaei Botanical Gardens": "https://www.tripadvisor.com/Attraction_Review-g29556-d554677-Reviews-Matthaei_Botanical_Gardens-Ann_Arbor_Michigan.html",
"Cherry Republic - Ann Arbor": "https://www.tripadvisor.com/Attraction_Review-g29556-d10053334-Reviews-Cherry_Republic_of_Ann_Arbor-Ann_Arbor_Michigan.html",
"Michigan Theater": "https://www.tripadvisor.com/Attraction_Review-g29556-d4761818-Reviews-Michigan_Theater-Ann_Arbor_Michigan.html",
"Ann Arbor Comedy Showcase": "https://www.tripadvisor.com/Attraction_Review-g29556-d10292854-Reviews-Ann_Arbor_Comedy_Showcase-Ann_Arbor_Michigan.html",
"The Ark": "https://www.tripadvisor.com/Attraction_Review-g29556-d268550-Reviews-The_Ark-Ann_Arbor_Michigan.html",
"Hill Auditorium": "https://www.tripadvisor.com/Attraction_Review-g29556-d7265010-Reviews-Hill_Auditorium-Ann_Arbor_Michigan.html",
"Gallup Park Canoe Livery": "https://www.tripadvisor.com/Attraction_Review-g29556-d559166-Reviews-Gallup_Canoe_Livery-Ann_Arbor_Michigan.html",
"Nickels Arcade": "https://www.tripadvisor.com/Attraction_Review-g29556-d10768004-Reviews-Nickels_Arcade-Ann_Arbor_Michigan.html",
"Blue LLama Jazz Club": "https://www.tripadvisor.com/Attraction_Review-g29556-d17237743-Reviews-Blue_LLama_Jazz_Club-Ann_Arbor_Michigan.html",
"Argo Canoe Livery": "https://www.tripadvisor.com/Attraction_Review-g29556-d559165-Reviews-Argo_Canoe_Livery-Ann_Arbor_Michigan.html",
"Gerald R. Ford Library": "https://www.tripadvisor.com/Attraction_Review-g29556-d8274536-Reviews-Gerald_R_Ford_Presidential_Library-Ann_Arbor_Michigan.html",
"Pedal Saloon Ann Arbor": "https://www.tripadvisor.com/Attraction_Review-g29556-d8596556-Reviews-Pedal_Saloon-Ann_Arbor_Michigan.html",
"University of Michigan Museum of Natural History": "https://www.tripadvisor.com/Attraction_Review-g29556-d268546-Reviews-University_of_Michigan_Museum_of_Natural_History-Ann_Arbor_Michigan.html",
"Nichols Arboretum": "https://www.tripadvisor.com/Attraction_Review-g29556-d10719589-Reviews-Nichols_Arboretum-Ann_Arbor_Michigan.html",
"Ann Arbor Farmers Market": "https://www.tripadvisor.com/Attraction_Review-g29556-d12712811-Reviews-Ann_Arbor_Farmers_Market-Ann_Arbor_Michigan.html",
"Briarwood Mall": "https://www.tripadvisor.com/Attraction_Review-g29556-d6905089-Reviews-Briarwood_Mall-Ann_Arbor_Michigan.html",
"Clueless Escape Rooms": "https://www.tripadvisor.com/Attraction_Review-g29556-d9740860-Reviews-Clueless_Escape_Rooms-Ann_Arbor_Michigan.html",
"Literati Bookstore": "https://www.tripadvisor.com/Attraction_Review-g29556-d8863823-Reviews-Literati_Bookstore-Ann_Arbor_Michigan.html",
"Kelsey Museum of Archaeology": "https://www.tripadvisor.com/Attraction_Review-g29556-d554671-Reviews-Kelsey_Museum_of_Archaeology-Ann_Arbor_Michigan.html",
"University of Michigan Museum of Art": "https://www.tripadvisor.com/Attraction_Review-g29556-d268547-Reviews-University_of_Michigan_Museum_of_Art-Ann_Arbor_Michigan.html",
"Hudson Mills Metropark": "https://www.tripadvisor.com/Attraction_Review-g29556-d554662-Reviews-Hudson_Mills_Metropark-Ann_Arbor_Michigan.html",
"The Creature Conservancy": "https://www.tripadvisor.com/Attraction_Review-g29556-d3845999-Reviews-The_Creature_Conservancy-Ann_Arbor_Michigan.html",
"Cobblestone Farm and Museum": "https://www.tripadvisor.com/Attraction_Review-g29556-d549247-Reviews-Cobblestone_Farm-Ann_Arbor_Michigan.html",
"Argus Farm Stop": "https://www.tripadvisor.com/Attraction_Review-g29556-d9583131-Reviews-Argus_Farm_Stop-Ann_Arbor_Michigan.html",
"Dawn Treader Book Shop": "https://www.tripadvisor.com/Attraction_Review-g29556-d7949352-Reviews-Dawn_Treader_Book_Shop-Ann_Arbor_Michigan.html",
"Lillie Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d12666553-Reviews-Lillie_Park-Ann_Arbor_Michigan.html",
"Vault of Midnight Comic Books and Stuff": "https://www.tripadvisor.com/Attraction_Review-g29556-d13570394-Reviews-Vault_of_Midnight-Ann_Arbor_Michigan.html",
"Yost Ice Arena": "https://www.tripadvisor.com/Attraction_Review-g29556-d5967778-Reviews-Yost_Ice_Arena-Ann_Arbor_Michigan.html",
"Lydia Mendelssohn Theatre": "https://www.tripadvisor.com/Attraction_Review-g29556-d8756577-Reviews-Lydia_Mendelssohn_Theatre-Ann_Arbor_Michigan.html",
"Delhi Metropark": "https://www.tripadvisor.com/Attraction_Review-g29556-d554660-Reviews-Delhi_Metropark-Ann_Arbor_Michigan.html",
"Barton Nature Area": "https://www.tripadvisor.com/Attraction_Review-g29556-d13992385-Reviews-Barton_Nature_Area-Ann_Arbor_Michigan.html",
"The Necto Night Club": "https://www.tripadvisor.com/Attraction_Review-g29556-d2663052-Reviews-Necto_Nightclub-Ann_Arbor_Michigan.html",
"Zingermans Bakehouse": "https://www.tripadvisor.com/Attraction_Review-g29556-d2688876-Reviews-BAKE_at_Zingerman_s_Bakehouse-Ann_Arbor_Michigan.html",
"Buhr Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d549267-Reviews-Buhr_Park-Ann_Arbor_Michigan.html",
"The M Den on Campus": "https://www.tripadvisor.com/Attraction_Review-g29556-d7194985-Reviews-The_M_Den-Ann_Arbor_Michigan.html",
"Kempf House Center For Local History": "https://www.tripadvisor.com/Attraction_Review-g29556-d554663-Reviews-Kempf_House-Ann_Arbor_Michigan.html",
"Nightcap": "https://www.tripadvisor.com/Attraction_Review-g29556-d16730434-Reviews-Nightcap-Ann_Arbor_Michigan.html",
"Dexter-Huron Metropark": "https://www.tripadvisor.com/Attraction_Review-g42141-d554661-Reviews-Dexter_Huron_Metropark-Dexter_Michigan.html",
"The Petting Farm at Domino's Farms": "https://www.tripadvisor.com/Attraction_Review-g29556-d8635870-Reviews-The_Petting_Farm_at_Domino_s_Farms-Ann_Arbor_Michigan.html",
"Mary Beth Doyle Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d12350682-Reviews-Mary_Beth_Doyle_Park-Ann_Arbor_Michigan.html",
"West Side Book Shop": "https://www.tripadvisor.com/Attraction_Review-g29556-d15701137-Reviews-West_Side_Book_Shop-Ann_Arbor_Michigan.html",
"Graffiti Alley": "https://www.tripadvisor.com/Attraction_Review-g29556-d17805228-Reviews-Graffiti_Alley-Ann_Arbor_Michigan.html",
"Washtenaw County -Meri Lou Murray - Recreation Center": "https://www.tripadvisor.com/Attraction_Review-g29556-d14832741-Reviews-Meri_Lou_Murray_Recreation_Center-Ann_Arbor_Michigan.html",
"LIVE": "https://www.tripadvisor.com/Attraction_Review-g29556-d13231021-Reviews-Live-Ann_Arbor_Michigan.html",
"County Farm Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d12620571-Reviews-County_Farm_Park-Ann_Arbor_Michigan.html",
"16 Hands": "https://www.tripadvisor.com/Attraction_Review-g29556-d10745308-Reviews-16_Hands-Ann_Arbor_Michigan.html",
"Rave Cinemas Ann Arbor": "https://www.tripadvisor.com/Attraction_Review-g42837-d13976435-Reviews-Rave_Cinemas_Ann_Arbor_20_Imax-Ypsilanti_Michigan.html",
"Leslie Science & Nature Center": "https://www.tripadvisor.com/Attraction_Review-g29556-d549258-Reviews-Leslie_Science_Center-Ann_Arbor_Michigan.html",
"Parker Mill County Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d10800743-Reviews-Parker_Mill_Park-Ann_Arbor_Michigan.html",
"Catching Fireflies": "https://www.tripadvisor.com/Attraction_Review-g29556-d20152822-Reviews-Catching_Fireflies-Ann_Arbor_Michigan.html",
"Bandemer Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d14002550-Reviews-Bandemer_Park-Ann_Arbor_Michigan.html",
"The Blue Leprechaun": "https://www.tripadvisor.com/Attraction_Review-g29556-d5841615-Reviews-The_Blue_Leprechaun-Ann_Arbor_Michigan.html",
"Dolph Park": "https://www.tripadvisor.com/Attraction_Review-g29556-d14784155-Reviews-Dolph_Nature_Area-Ann_Arbor_Michigan.html",
"Pinball Pete's": "https://www.tripadvisor.com/Attraction_Review-g29556-d10798807-Reviews-Pinball_Petes-Ann_Arbor_Michigan.html",
"Emagine - Saline": "https://www.tripadvisor.com/Attraction_Review-g42676-d12249375-Reviews-Emagine_Theatres_Saline-Saline_Michigan.html",
"Revel & Roll": "https://www.tripadvisor.com/Attraction_Review-g29556-d6080396-Reviews-Revel_Roll-Ann_Arbor_Michigan.html",
"Encore Records": "https://www.tripadvisor.com/Attraction_Review-g29556-d13939829-Reviews-Encore_Records-Ann_Arbor_Michigan.html",
"Furstenberg Nature Area": "https://www.tripadvisor.com/Attraction_Review-g29556-d9739378-Reviews-Furstenberg_Nature_Area-Ann_Arbor_Michigan.html",
"Planet Rock": "https://www.tripadvisor.com/Attraction_Review-g29556-d12972010-Reviews-Planet_Rock-Ann_Arbor_Michigan.html",
"The State Theatre": "https://www.tripadvisor.com/Attraction_Review-g29556-d14018084-Reviews-State_Theatre-Ann_Arbor_Michigan.html",
"Rock Paper Scissors": "https://www.tripadvisor.com/Attraction_Review-g29556-d15027313-Reviews-Rock_Paper_Scissors-Ann_Arbor_Michigan.html",
"Theatre Nova": "https://www.tripadvisor.com/Attraction_Review-g29556-d10839631-Reviews-Theatre_Nova-Ann_Arbor_Michigan.html",
"Museum on Main Street": "https://www.tripadvisor.com/Attraction_Review-g29556-d8308704-Reviews-Museum_on_Main_Street-Ann_Arbor_Michigan.html",
"BeeQ Downtown A2": "https://www.tripadvisor.com/Attraction_Review-g29556-d17665535-Reviews-BeeQ_Spa-Ann_Arbor_Michigan.html",
"Axe Ventura": "https://www.tripadvisor.com/Attraction_Review-g29556-d19656552-Reviews-Axe_Ventura-Ann_Arbor_Michigan.html",
"Bird Hills Nature Area": "https://www.tripadvisor.com/Attraction_Review-g29556-d14765233-Reviews-Bird_Hills_Nature_Area-Ann_Arbor_Michigan.html",
"Crazy Wisdom Bookstore": "https://www.tripadvisor.com/Attraction_Review-g29556-d269530-Reviews-Crazy_Wisdom_Bookstore_Tearoom-Ann_Arbor_Michigan.html",
"Kidopolis": "https://www.tripadvisor.com/Attraction_Review-g29556-d11871227-Reviews-Kidopolis-Ann_Arbor_Michigan.html",
"Arthur Miller Theatre": "https://www.tripadvisor.com/Attraction_Review-g29556-d14788319-Reviews-Arthur_Miller_Theatre-Ann_Arbor_Michigan.html",
"Ypsilanti Historical Museum": "https://www.tripadvisor.com/Attraction_Review-g42837-d12487606-Reviews-Ypsilanti_Historical_Museum_and_Archives-Ypsilanti_Michigan.html",
"Michigan Firehouse Museum": "https://www.tripadvisor.com/Attraction_Review-g42837-d2711246-Reviews-Michigan_Firehouse_Museum-Ypsilanti_Michigan.html",
"Ypsilanti Automotive Heritage Collection": "https://www.tripadvisor.com/Attraction_Review-g42837-d7360653-Reviews-Ypsilanti_Automotive_Heritage_Museum-Ypsilanti_Michigan.html",
"North Hydro Park": "https://www.tripadvisor.com/Attraction_Review-g42837-d15328013-Reviews-North_Hydro_Park-Ypsilanti_Michigan.html",
"Tipsy Ypsi Paint & Pour": "https://www.tripadvisor.com/Attraction_Review-g42837-d19106239-Reviews-Tipsy_Ypsi_Paint_Pour-Ypsilanti_Michigan.html",
"Powell's Pub": "https://www.tripadvisor.com/Attraction_Review-g42837-d5846083-Reviews-Powell_s_Pub-Ypsilanti_Michigan.html",
"Curtiss Park": "https://www.tripadvisor.com/Attraction_Review-g42676-d15027027-Reviews-Curtiss_Park-Saline_Michigan.html",
"McPherson Local": "https://www.tripadvisor.com/Attraction_Review-g42676-d20086081-Reviews-McPherson_Local-Saline_Michigan.html",
"Independence Lake County Park": "https://www.tripadvisor.com/Attraction_Review-g42822-d12948554-Reviews-Independence_Lake_County_Park-Whitmore_Lake_Michigan.html"}